#!/bin/bash
# Purpose - Script to create a wordpress site on Ubuntu using Nginx, Mariadb and PHP
# Author - denuvo under GPL v3.0+
# ------------------------------------------------------------------
# Am i Root user?

apt update
DEBIAN_FRONTEND=noninteractive apt -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
read -p "Enter hostname : " hostname
hostnamectl set-hostname $hostname
hostname -F /etc/hostname
ips=$(ip -o -4 addr show up primary scope global |
      while read -r num dev fam addr rest; do echo ${addr%/*}; done)
if [ $(id -u) -eq 0 ]; then
	read -p "Enter username : " username
	read -p "Enter password : " password
	egrep "^$username" /etc/passwd >/dev/null
	if [ $? -eq 0 ]; then
		echo "$username exists!"
		exit 1
	else
		pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
		useradd -m -p "$pass" "$username"
		[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
	fi
else
	echo "Only root may add a user to the system."
	exit 2
fi
usermod -a -G sudo $username
